### ISSUE TITLE
Open source checklist

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/asset-tokenization-studio#1]
- [x] Readme (include a code of conduct and contributing guide section)
- [x] DCO
- [x] Licence file
- [x] Licence headers

- [x] SonarQube
- [x] Github actions
- [x] Code Coverage
- [x] Branch protection rules
- [x] Add project to Hedera docs site when live (if required)
- [ ] ~~Standardize package name (com.hedera.<name>) (if applicable)~~
- [x] Add [security.md](http://security.md/) file if the project is not going to be part of the bug bounty program
- [ ] ~~Approval from council (if required)~~
- [x] Code audit (if required)

- [x] Open source project

**Comment by andrewb1269hg** [comment]
Issue #17 was closed in Nov. 2024. We can proceed with this issue.
